### ISSUE TITLE
`RpcConn::try_get_*` functions don't get messages from the unix socket

### ISSUE THREAD

**Issue by cmaves** [KillingSpark/rustbus#16]
After reading the description of `RpcConn::try_get_call()`, I assumed that this function would retrieve messages that were sent from DBus that were waiting, process them and return any calls that were waiting. Instead this function only pops a message from the calls VecDeque, but doesn't process any messages from the Unix socket. 

If you repeatably call `RpcConn::try_get_*()`, but never call any of the wait functions, then messages from DBus will build up in the unix socket buffer but never be processed. This strikes me as uninitutive because in order to understand what the try_get function do, you need to understand the underlying implementation of the rustbus message queues.

**Comment by KillingSpark** [comment]
That is true, and it should be possible to implement that with the existing lower level Conn struct.

So try_get_*() should make some progress if there is data on the unix socket, but it might still return None. The question is how much progress should we make per call?
1.  Decode all messages until the socket has no more data available
2. Decode at most one message

I am leaning towards  2.) since the try_get_*() are intended to be cheap.

Another possibility is to do it like libdbus does it. The different try_get_* roughly correspond to the dispatch() call they have where buffered messages get distributed to their handlers. They have a read_write() call that actually does IO and buffers received messages. That would correspond to the (currently private) refill() call on RpcConn. So rustbus would expose the refill() publicly and mention that explicitly in the doc for the try_get_*().

Currently refill() only reads one message at a time so a second function, that calls refill until no more data is available on the socket could be exposed too. 

I think I prefer the libdbus way, because it gives the user more control over when IO is performed, and the try_get_* functions remain very cheap.

**Comment by cmaves** [comment]
I also like the libdbus way and think it would be a good approach, but I think that it would also be helpful to either add additional IO functions or beef up the refill() method if it is going to be exposed. Currently refill will only read one (non-filtered) message at a time in a blocking manner. It is kinda hard to use in an ergonomic way if somebody wants finer control of IO from the UnixSocket.

It would be nice if refill()  (or some new function) could retrieve multiple messages with a single call, so users of the crate can make a larger reads without having to loop over refill. Retrieving multiple messages at a time can also open the door to some IO optimization. Rather than reading one message at time in short 512 byte blocks would could make significantly large reads that retrieve multiple messages in a single syscall, rather than having to make numerous calls. Adding the ability to make non-blocking reads would also be valuable to users who want to have finer control over their IO

**Comment by KillingSpark** [comment]
I too think that a wrapper around refill, that drains the socket completely, would be the best way to expose this.

I would love to make bigger reads on the socket. Unfortunately it is not  possible to read multiple messages at once, because messages need to be read exactly to make filedescriptor passing possible. The way that those are matched to reads is a bit under-specified and differs between linux/bsd/...

I could probably make the reads more efficient by passing 'msg_buf_in: Vec<u8>' into the IoVec instead of using the local [u8;512]. I am not sure if this is a big limitation though.

**Comment by KillingSpark** [comment]
Could you take a look at the changes made in 2d2b1c7bb362e5e323db292a7f712ef653571066 ? The refill_*() functions should allow for fine control over when and how IO is performed.

**Comment by cmaves** [comment]
It looks great. The changes the IO timing with the Timeout struct look good. 

I also like the refill_* functions. The only thing that I am unsure about is if returning a Vec responses is the best way to handle error responses for filtered messages in refill_all(). The function is intended as a convenience function but adds an extra step to use it for uses of the library. In the short term this is probably fine, but it is something to think about improving.

The only solution I could think of would be to add an outbound queue of messages, and a set of functions to flush those messages out to the socket (like refill functions but for writes instead of reads). However this strikes me a beyond the scope of this issue and something to consider in the future.

**Comment by KillingSpark** [comment]
Glad you like it!

Yes, while refactoring this code, I noticed that the other handling of error-replies is somewhat wacky too if the timeouts are small. Having an outgoing queue seems like a good idea. I will think about this a bit and see what I come up with. But you're right that is out of scope for this issue.
