### ISSUE TITLE
Add ability to connect to DBus on abstract unix socket

### ISSUE THREAD

**Issue by jabedude** [KillingSpark/rustbus#17]
Currently `get_session_bus_path` does not support abstract unix addresses such as: 
`sess path: "unix:abstract=/tmp/dbus-nzcZ2pXz20,guid=eac3a82b1833828074d055075eb19a02"`.

This would be a small fix if the rust stdlib `UnixStream::connect` supported abstract sockets, but it doesn't appear to. The `nix` crate does support abstract UDS, but switching to use `nix` would change a fair bit of code so I wanted to open an issue to see what you thought first :)

I started a WIP branch here: https://github.com/jabedude/rustbus/tree/abstract-socket

**Comment by KillingSpark** [comment]
I am always for having better compatibility with the dbus ecosystem :) 

It is nice that the nix crate supports abstract UDS but they fail to provide a RAII wrapper around their RawFds. A simple wrapper that closes the fd if the wrapper gets dropped would be enough.

What you could try to do, what would not need much code changes is to open the abstract socket with nix, and use [FromRawFd](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html) to crate a [streaming unix socket](https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html). I dont know if this creates any issues, because the std only expects filesystem UDS, but I think it should be ok?
