### ISSUE TITLE
Cannot marshal a variant containing an UnixFd

### ISSUE THREAD

**Issue by gmambro** [KillingSpark/rustbus#25]
Seems There is no support for Token::UnixFd in https://github.com/KillingSpark/rustbus/blob/c2e28f32ad6f3baab9bc0b927dffc3ac6c5a45e2/src/signature.rs#L299
 and I get errors when marshalling a variant containing a fd, like in this case.
```
  Container( Struct(  [
     Base(  StringRef( "StandardErrorFileDescriptor"  ),   ),
     Container(  Variant(  Variant {   
             sig: Base(   UnixFd  ),
             value: Base( UnixFd( 0 )  ),
       }  )  ),
] )  ),
```

**Comment by KillingSpark** [comment]
Hey, that is correct, that code should support Token::UnixFd. But just to make this clear (because dbus is weird in that regard) you should not put an actual filedescriptor in there. The unixfd type is just meant to represent an index into the raw filedescriptors in the message, that get transmitted outside the actual message [see the description of the UNIX_FD type here](https://dbus.freedesktop.org/doc/dbus-specification.html#basic-types).

Thanks for the report I will fix this soon.

**Comment by KillingSpark** [comment]
There is an example for how to send fds with rustbus [here](https://github.com/KillingSpark/rustbus/blob/master/examples/fd.rs). Basically you just add them to the message and set the num_fds of the message to the correct number. They will be delivered the same on the other side. 

This is currently a bit rough API wise, there should be a function that adds fds and takes care of keeping track of the number of fds by itself.

**Comment by gmambro** [comment]
Thank you for  looking into this. I wrote a crate to talk to systemd using rustbus (not ready to be opensourced yet) and the example helped a lot. Also even if the API was a bit rough it allows writing a serialisation layer (I used the old interface for params).
it stopped working when I updated rustbus and this is how I spotted this issue.

**Comment by KillingSpark** [comment]
Could you try it with commit 3ba866f079361fcd41345c00b74cf9a60ba32e18 ? This should fix your issue. 

I don't quite understand how that worked before, that line was just plainly missing, maybe an error was made while refactoring. In any case, I am sorry for the inconvenience.

**Comment by gmambro** [comment]
Yep, it works!
