### ISSUE TITLE
need one more example

### ISSUE THREAD

**Issue by okeri** [KillingSpark/rustbus#42]
Hello. I have some code using old rustbus version, now i'm trying to update to recent one, and wondering i still cannot get rid of some code duplication of rustbus::client_conn. May be i missed something about dbus specs, but coult you make one more example of using rustbus? My main goal is to develop service, it accepts some method calls and emits some events asynchronically (in another thread), so external interface should be looks like this:

```xml
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">  
<node name="/mynode">  
  <interface name="my.interface.name">  
    <method name="mymethod">  
    </method>  
    <signal name="myevent">  
    </signal>  
  </interface>  
</node>
```
Is it possible to implement this interface using rustbus ? The problem is i don't know how to share rustbus::client_conn::Conn between threads, while one of them is emitting signals, and another one is waiting for incoming method calls. Thanks.

**Comment by KillingSpark** [comment]
I guess you could wrap the conn in a `Arc<Mutex<Conn>>`. This has a lot of drawbacks though, because you'd need to lock it to wait for messages. You might want to just open two conns, one for receiving and one for sending the events. This is admittedly not a good solution. The support for services is yet lacking in this lib. It is the next thing I wanted to work on anyways, so you can probably expect more convenience in the future.

**Comment by okeri** [comment]
Ok. thank you for answer, so i will wait for your further steps in this direction.
