### ISSUE TITLE
Use of `Rc` instead `Arc` makes `Param` difficult to use with w/ threading

### ISSUE THREAD

**Issue by htejun** [KillingSpark/rustbus#49]
Hello,

In the process of converting a program to rustbus, I'm having difficulties w/ Param's embedded in another struct as a dbus response cache. The containing struct can be accessed from multiple threads and protected with Mutex. However, the use of Rc in rustbus makes that impossible leading to an error as below:
```
error[E0277]: `std::rc::Rc<rustbus::wire::unixfd::UnixFdInner>` cannot be sent between threads safely
```
I think the problem can be resolved by using Arc instead of Rc.

Thank you.

**Comment by KillingSpark** [comment]
Hi,
This should be fixable with using `Arc` instead of `Rc`. Do note though, that the cache might not function as you intend it to, if you work with the `UnixFd`. Taking the FD out of it only works once (to ensure proper closing of the FDs by leveraging ownership rules) which is probably counter-intuitive for a cache.

**Comment by KillingSpark** [comment]
I am not sure when I will get to fixing this, in the meantime you can copy the implementation (and the relevant Marshal + Unmarshal impls) for UnixFd from rustbus and change Rc to Arc. It's no that much code really.

**Comment by htejun** [comment]
Oh, I'm caching systemd unit properties response, so nothing fancy, just strings and numbers. For the time being, I built a separate enum for caching the properties. I'll switch over to rustbus Param when it gets updated. Thanks!

**Comment by KillingSpark** [comment]
Oh, you want to use the params::Param enums? You might want to look into the trait based Unmarshalling, to make this easier. I kept these enums around for cases that the newer mechanism might not support, I might phase them out entirely in future if I am confident the traits can cover every case.

**Comment by htejun** [comment]
Yeah, I tried to use the Unmarshalling based one but couldn't figure out how to handle the layout used by `StartTransientUnit` call. https://pastebin.com/5yRaav6s is the test code I've been tinkering with (I'm trying to replace dbus crate w/ rustbus for https://github.com/facebookexperimental/resctl-demo/blob/master/util/src/systemd.rs).

Please take a look at systemd_start_transient_svc_call(). The dbus call signature is "ssa(sv)a(sa(sv))" and the middle v has mixed of different types including "sasb". I couldn't figure out how to do that w/ the trait. Another problem is the "GetAll" call which returns all systemd unit properties. Here, the problem is that in this layer I'm not quite sure what to expect, cache the result and let the users query what they need.

Making the enums work was painful so I'm all ears for a better approach. Thanks!

**Comment by htejun** [comment]
FWIW, I landed the PR to switch resctl-demo to rustbus: https://github.com/facebookexperimental/resctl-demo/pull/137

It's more wordy but works really well as a replacement. I'd be happy to update further if there is a better way w/ the trait based marshalling. Thanks.

**Comment by KillingSpark** [comment]
> Please take a look at systemd_start_transient_svc_call(). The dbus call signature is "ssa(sv)a(sa(sv))" and the middle v has mixture of different types including "sa(s)b". I couldn't figure out how to do that w/ the trait. 

I'll definitely have a look! There is a handy `Variant` struct cmaves contributed, it is not yet very visible and I need to write more examples around this stuff. It does however bind the Variants lifetime to that of the message, so that might be bad if you want to only cache the actual unmarshalled values and not the messages. It might be possible to generate the variants here with the `macro_rule! dbus_variant` though. I'll report back when I had a look at the code.

> Another problem is the "GetAll" call which returns all systemd unit properties. Here, the problem is that in this layer I'm not quite sure what to expect, and want to cache the result and let the users query what they need.

Here you might actually need to use the enums, which is unfortunate. But it is definitely good to have these usecases to guide further development. I'll see if I can come up with something helpful.

> FWIW, I landed the PR to switch resctl-demo to rustbus: facebookexperimental/resctl-demo#137 

That is really cool. Always happy to see people use my stuff :)

**Comment by KillingSpark** [comment]
Oh sorry I did not realize that `ssa(sv)a(sa(sv))` was the calling signature not that of the returned values. In this case `dbus_variant!` should work nicely.  I tried to convert it to the trait based marshalling. I noticed that there was an `impl Marshal` missing for Vev<E: Marshal>, so this code does not yet compile. I'll push that to master soon and make a new release so you can use it.

```rust
use rustbus::message_builder;
use rustbus::message_builder::MarshalledMessage;
use rustbus::params;
use rustbus::signature;

// a typedef for the complicated case
type ExecStartProp = Vec<(String, Vec<String>, bool)>;

// define the variant with a fitting marshal and unmarshal impl
rustbus::dbus_variant_sig!(TransientServiceCallProp, String => String; StringList => Vec<String>; ExecStart => ExecStartProp);

const SD1_DST: &str = "org.freedesktop.systemd1";
const SD1_PATH: &str = "/org/freedesktop/systemd1";

fn systemd_sd1_call(method: &str) -> MarshalledMessage {
    message_builder::MessageBuilder::new()
        .call(method.into())
        .with_interface("org.freedesktop.systemd1.Manager".into())
        .on(SD1_PATH.into())
        .at(SD1_DST.into())
        .build()
}

fn dbus_param_array<'a, 'e>(param: params::Array<'a, 'e>) -> params::Param<'a, 'e> {
    params::Param::Container(params::Container::Array(param))
}

fn dbus_sig(input: &str) -> signature::Type {
    signature::Type::parse_description(input).as_ref().unwrap()[0].clone()
}

fn systemd_start_transient_svc_call(
    name: String,
    args: Vec<String>,
    envs: Vec<String>,
    extra_props: Vec<(String, TransientServiceCallProp)>,
) -> MarshalledMessage {
    // NAME(s) JOB_MODE(s) PROPS(a(sv)) AUX_UNITS(a(s a(sv)))
    //
    // PROPS:
    // ["Description"] = str,
    // ["Slice"] = str,
    // ["CPUWeight"] = num,
    // ...
    // ["Environment"] = ([ENV0]=str, [ENV1]=str...)
    // ["ExecStart"] = (args[0], (args[0], args[1], ...), false)
    let mut call = systemd_sd1_call("StartTransientUnit");

    // name and job_mode
    call.body.push_param2(&name, "fail").unwrap();

    // desc string
    let desc = args.iter().fold(name.clone(), |mut a, i| {
        a += " ";
        a += i;
        a
    });

    let mut props = vec![
        (
            "Description".to_owned(),
            TransientServiceCallProp::String(desc),
        ),
        (
            "Environment".to_owned(),
            TransientServiceCallProp::StringList(envs),
        ),
        (
            "ExecStart".to_owned(),
            TransientServiceCallProp::ExecStart(vec![(args[0].clone(), args, false)]),
        ),
    ];

    for prop in extra_props.into_iter() {
        props.push(prop);
    }

    // assemble props
    call.body.push_param(props).unwrap();

    // no aux units
    call.body
        .push_old_param(&dbus_param_array(params::Array {
            element_sig: dbus_sig("(sa(sv))"),
            values: vec![],
        }))
        .unwrap();

    call
}
```

**Comment by KillingSpark** [comment]
Ok I pushed a new release 0.9.2 that allows this code to compile. If you have any question on this / other parts I am happy to help :)

**Comment by cmaves** [comment]
It is worth noting that even if htejun's problem doesn't end up needing `UnixFd` being `Send` it maybe worth it to do it anyway for ergonomics. UnixFd could be made `Send` and `Sync` by using an AtomicI32 instead of a `Cell<Option<RawFd>>` in the inner struct (avoiding the Mutex) and allowing `Arc` to be used instead.

**Comment by htejun** [comment]
Applied the suggested changes. That's so much better. Thank you.

One more possibly silly question: Would it be possible to add Clone to the macro generated enum? Maybe it needs to be optional but that'd allow using the generated enum as the type to carry / store unit properties.

**Comment by KillingSpark** [comment]
That might be possible with a bit of breaking changes. What I was planning to do was to create a derive proc-macro like I have for structs. The `dbus_variant` macro was created when I was just diving into the whole macro ecosystem and macrorules! seemed easier at first. Now that the `rustbus_derive` crate exists, adding a derive for enums should be relatively easy.

For now you'll sadly need to make an equivalent enum that you can create from the generated enum. That might be worthwhile anyways since the generated enum contains a `Catchall` case, which takes any variant that did not match any of the cases you specified in the macro call. You will probably want to deal with them before storing the enum somewhere else

**Comment by KillingSpark** [comment]
On the original issue: I started doing some work on making UnixFd `Send + Sync` in the branch `split_conn`. I dont think that will take long to merge into master and get a new release.

**Comment by KillingSpark** [comment]
So this is in the master branch now, but not yet in a release. The next release should not take too long though :)

**Comment by KillingSpark** [comment]
So this is in the v0.12.0 release which is also available on crates.io

I hope this fixes your issue
