### ISSUE TITLE
Marshal is not Object-Safe

### ISSUE THREAD

**Issue by KillingSpark** [KillingSpark/rustbus#91]

**Comment by MaxVerevkin** [comment]
To make it object-safe `Signature`'s associated functions would need to become methods, I think. This would also make it possible to implement `Signature` for `Param`, which in turn would make `push_old_param()` fully obsolete.

**Comment by MaxVerevkin** [comment]
> To make it object-safe `Signature`'s associated functions would need to become methods, I think. This would also make it possible to implement `Signature` for `Param`, which in turn would make `push_old_param()` fully obsolete.

Apparently it is not that simple, some code requires signature functions to be associated, for example `unmarshal::traits::Variant::get`, because there is no value of `T` to get the signature from.

From the first glance solving this would require duplicating the `Signature` trait: one object-safe and one not :( Not sure if this is worth it.

**Comment by KillingSpark** [comment]
Yeah I think I ran up against that wall at least once before. I think this won't be fixable without a rewrite of a significant part of the codebase
