### ISSUE TITLE
Benchmark is broken

### ISSUE THREAD

**Issue by MaxVerevkin** [KillingSpark/rustbus#94]
```
Benchmarking unmarshal: Warming up for 3.0000 sthread 'main' panicked at rustbus/benches/marshal_benchmark.rs:18:82:
called `Result::unwrap()` on an `Err` value: NotEnoughBytes
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by KillingSpark** [comment]
Damn, that's obviously not good, but the current benchmarking is taking place here: https://github.com/KillingSpark/rust-dbus-comparisons

I'll copy over the benchmark from there

**Comment by KillingSpark** [comment]
So I did not copy the benchmark from the comparison repo because I noticed that that doesn't even have unmarshal benchmarks. I think the comparison repo should be extended to contain benchmarks for unmarshalling and we should remove the benchmarks from this repo entirely (to reduce code duplication and cut a lot of dev-dependecies)
